---
apiVersion: v1
kind: Service
metadata:
  name: snyky-service
  labels:
    app.kubernetes.io/name: snyky-service
    helm.sh/chart: snyky-service-0.1.0
    app.kubernetes.io/instance: snyky-service
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/managed-by: Tiller
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: snyky-service
    app.kubernetes.io/instance: snyky-service

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "snyk-charts.fullname" . }}
  labels:
    {{- include "snyk-charts.labels" . | nindent 4 }}
spec:
  hostPID: {{ .Values.hostPID }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "snyk-charts.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "snyk-charts.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "snyk-charts.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
