dependencies:
  - name: wordpress
    version: 5.0.2
    repository: https://kubernetes-charts.storage.googleapis.com
  - name: mariadb
    version: 5.x.x
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: mariadb.enabled
    tags:
      - wordpress-database
  - name: prometheus
    repository: https://kubernetes-charts.storage.googleapis.com/
    version: '>= 8.9.2'
